syntax = "proto3";

package nn.proto;

message Model {
  uint32 format_version = 1;
  repeated Layer layers = 2;
}

message Layer {
  LayerRecipe recipe = 1;
  Parameters parameters = 2;
}

message LayerRecipe {
  string name = 1;
  string type = 2;
  string info = 3;
  string activation = 4;

  repeated uint64 input_shape = 5;
  repeated uint64 output_shape = 6;

  oneof kind {
    DenseLayer dense = 10;
    ConvolutionalLayer convolutional = 11;
    FlattenLayer flatten = 12;
    HopfieldLayer hopfield = 13;
  }
}

message Parameters {
  Tensor weights = 1;
  Tensor biases = 2;
}

message Tensor {
  repeated uint64 shape = 1;
  repeated float values = 2;
}

message DenseLayer {
}

message FlattenLayer {
}

message HopfieldLayer {
}

message ConvolutionalLayer {
  uint64 kernel_size = 4;
  uint64 stride = 5;
  uint64 padding = 6;
}



